spring:
  banner:
    charset: utf-8
    location: classpath:/config/banner.txt
# DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/zy?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123pjzy
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 100
    dbcp2:
      initial-size: 2
      max-wait-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: false
      validation-query: SELECT 1 from dual
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
    tomcat:
      validation-query: SELECT 1 from dual
    test1:
      jdbcUrl: jdbc:mysql://localhost:3306/multipledatasource1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123pjzy
#      driver-class-name: com.mysql.cj.jdbc.Driver
      driverClassName: com.mysql.cj.jdbc.Driver
    test2:
      jdbcUrl: jdbc:mysql://localhost:3306/multipledatasource2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123pjzy
#      driver-class-name: com.mysql.cj.jdbc.Driver
      driverClassName: com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
# Specify the DBMS
  jpa:
    database: MYSQL
# Show or not log for each sql query
    show-sql: true
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: validate
  application:
# 应用程序名称。
    name: sb
# 添加@EnableAspectJAutoProxy。
  aop:
    auto: true
  redis:
    timeout: 60000ms
    database: 1
    host: localhost
    password: pwd
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
#    cluster:
  ##单服务器
#      nodes: 192.168.159.129:7001,192.168.159.129:7002,192.168.159.129:7003,192.168.159.129:7004,192.168.159.129:7005,192.168.159.129:7006
#    jedis:
#      pool:

  ## 连接池最大连接数（使用负值表示没有限制）
#        max-active: 300
  ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
  ## 连接池中的最大空闲连接
#        max-idle: 100
  ## 连接池中的最小空闲连接
#        min-idle: 20
  ## Redis数据库索引(默认为0)
#      database: 0
  ## 连接超时时间（毫秒）
  session:
    redis:
      flush-mode: no_save
      #添加后，redis中的key为spring:session:springboot
      namespace: springboot
    store-type: redis

server:
  port: 8080
jwt:
  header: Authorization
  tokenHead: Bearer
  secret: mySecret
  #满期 604800
  expiration: 10
  route:
    authentication:
      path: /auth
      refresh: /refresh
      register: /auth/register


